name: taskpipeline
description: Control future start or stop (not really, but return null immediately), that is really useful for development in fact.
version: 0.0.2
homepage: https://github.com/CimZzz/taskpipeline
author: wangyanxiong <a1950207@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
